### PR TITLE
Clarifies the thoughts around data storage

### PR DESCRIPTION
**Pull request by karfai**

### CODE REVIEW

**Comment by jpotvin** [comment]
RE: " only fetching from Mongo when detailed information about a document, table or rule is required"

Under what circumstances will this be necessary, and when it occurs, does it marginally reduce compute time the first time it is needed, after which a similar reach over to MongoDB won't be needed, because the data is in Cassandra's DB now?  If so, how does Cassandra stay synched to the latest Mongo data? When data in Mongo is updated, would it check for and version-update its copies over in Cassandra?

**Comment by jpotvin** [comment]
RE: "jurisdiction of a document"

What exactly does this mean?

**Comment by jpotvin** [comment]
RE: For *persistence-optimized* storage, the system employs MongoDB. This provides for storage of documents, tables and rules in a document-oriented format. 

Should that be "documents, tables and rules" or just "tables and rules". What "documents" will the data fabric's Mongo instance store that are not tables and rules?  ... will we also use this instance for storing other IoR "stuff"? (My hunch is that this instance ought to be dedicated to ONLY IoR tables and rules. Anything else should be in a different DB. This way, it seems to me that security rules enforcement can be more systematic. Anything that is more than a dumbdumb table exactlyt meeting the Xalgo spec should be flagged as an invader.)

RE: "Its data model is *very close* to the format in which the data is submitted to the system (discrete documents)."

This also makes security monitoring easier. But what does "very close" really mean? Can we specify in a couple of points here what is different?

**Comment by jpotvin** [comment]
RE: "Tables are stored as a JSON-like version of the CSV that was originally stored in the package repository."

Why "JSON-like" and not "JSON"?  And what is not JSON about it?  
Is it Pandas?
https://stackoverflow.com/questions/21104592/json-to-pandas-dataframe

**Comment by karfai** [comment]
> Under what circumstances will this be necessary, and when it occurs, does it marginally reduce compute time the first time it is needed, after which a similar reach over to MongoDB won't be needed, because the data is in Cassandra's DB now? If so, how does Cassandra stay synched to the latest Mongo data? When data in Mongo is updated, would it check for and version-update its copies over in Cassandra?

**Comment by karfai** [comment]
https://github.com/Xalgorithms/xa-arch/issues/20 captures the activity associated with this comment thread. Further questions can be added there.

**Comment by jpotvin** [comment]
I think sometimes you say "Cassandra" when you mean CQL, no?  Later when we move to SkyllaDB there will be fewer updates if we say CQL where we refer to the data.

**Pull request merged**
